/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import static Formularios.Confirmacion.montoea;
import static Formularios.Confirmacion.montoem;
import static Formularios.Confirmacion.montoen;

/**
 *
 * @author Michael
 */
public class Comprobante extends javax.swing.JFrame {

    /**
     * Creates new form Comprobante
     */
    public Comprobante() {
        initComponents();
        Comp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comprobante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comprobante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comprobante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comprobante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comprobante().setVisible(true);
            }
        });
    }
    
    public void Comp(){
        Entradas entradas = new Entradas();
        Dulcería dulceria = new Dulcería();
        montoen = entradas.niños * 9;
        montoea = entradas.adultos * 15;
        montoem = entradas.mayores * 10;
        double montodulceria = 0;
        montodulceria = (dulceria.cc1 * 19)+(dulceria.cc2*24)+(dulceria.cc3*28)+dulceria.cc4*10+dulceria.cc5*13+dulceria.cc6*7;
        double total = 0;
        total =     montodulceria+montoen+montoea+montoem;
        double igv =0;
        igv = total - (total * 0.18);
        
        
        String mensaje = "";
        
                jTextArea1.setText("-------------------Sistema de Ventas de CineStar ----------------"
                + "\n"+ "Entradas adquiridas para niños: "+entradas.niños+
                "\n"+"Entradas adquiridas para Adultos: "+entradas.adultos+
                "\n"+"Entradas adquiridas para Mayores de 60 años: "+entradas.mayores+
                "\n"+"Combos seleccionados: "+
                "\n"+"Combo 1: Combo 1 PopCorn Chico + 2 Botellas de Gaseosa: "+dulceria.cc1+
                "\n"+"Combo 2: Combo 2 PopCorn Gigante + 2 Botellas de Gaseosa: "+dulceria.cc2+
                "\n"+"Combo 3: Combo 3 PopCorn Gigante + 2 Botellas de Gaseosa + HotDog: "+dulceria.cc3+
                "\n"+"Combo 4: Combo 4 PopCorn Salado Grande: "+dulceria.cc4+
                "\n"+"Combo 5: Combo 5 PopCorn Gigante: "+dulceria.cc5+
                "\n"+"Combo 6: Gaseosa chica: "+dulceria.cc6+
                "\n"+"Precio Unitario Entradas: "+(montoen+montoea+montoem)+
                "\n"+"Precio Unitario Combos: "+montodulceria+
                "\n"+"IGV:"+igv+       
                "\n"+"Importe Total :"+ total);
        
        
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
